### ISSUE TITLE
feedupdater.py utf8 error

### ISSUE THREAD

**Issue by sachaz** [gehaxelt/python-rss2irc#46]
'ascii' codec can't encode character u'\xea' in position 40: ordinal not in range(128)

**Comment by MaxLeiter** [comment]
Same issue here.

**Comment by gehaxelt** [comment]
@sachaz @MaxLeiter Do you have more information on the issue? Like a certain line where the error occurs or something?

**Comment by Wibol** [comment]
This problem seems to affect only the display in the terminal, since the news are published using special characters.

It can be solved by adding a letter "_u_" just before of **every affected string** for unicode. For example:
`print(u"[+]: {}||{}||{}||{}".format(feed_title, news_title, news_url, news_date))`

It is necessary to do this in all files with this problem.

Very good job, gehaxelt. Thanks.

**Comment by gehaxelt** [comment]
@Wibol does this PR (https://github.com/gehaxelt/python-rss2irc/pull/50) fix it or are there more locations that need to be fixed?

**Comment by Wibol** [comment]
This line is also repeated in bot.py, class bot, def initial_feed_update and it is necessary to do the same.

That's all. Thank you.

**Comment by gehaxelt** [comment]
@Wibol okay, cool! 

I've merged the changes and hope that #50 resolved this issue. 

Thanks again for reporting the solution :-)
